[template]
mode = "0644"
src = "basic.conf.tmpl"
dest = "/tmp/confd-manykeys-test.conf"
keys = [
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username",
  "/stargate_test/database/host",
  "/stargate_test/database/password",
  "/stargate_test/database/port",
  "/stargate_test/database/username"
]
